@startuml Диаграмма деятельности (Оформление заказа)
start

if (Авторизован?) then (Нет)
  :Вход/Регистрация;
endif

:Просмотр каталога;
:Добавление книг в корзину;

:Просмотр корзины;

if (Корзина пуста?) then (Да)
  stop
else (Нет)
endif

:Заполнение формы заказа;
:Подтверждение;

:Создание заказа;
:Отправка уведомления;
:Очистка корзины;

stop

note right
  Процесс оформления заказа
end note
@enduml
